name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'isolate-lab/package-lock.json'
      - run: printenv
      - run: cd  /home/runner/work/v8isolate-lab/isolate-lab
      - run: sudo apt-get install sqlite3
      - run: sudo apt-get install g++ build-essential -y
      - run: npm ci
      - run: npm test
        env:
          UNAUTHORIZED_TOKEN: ${{ secrets.UNAUTHORIZED_TOKEN }}
          MALFORMED_TOKEN: ${{ secrets.MALFORMED_TOKEN }}
          CUSTOM_ENVVAR: 1234
