name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          UNAUTHORIZED_TOKEN: ${{ secrets.UNAUTHORIZED_TOKEN }}
          MALFORMED_TOKEN: ${{ secrets.MALFORMED_TOKEN }}
      - run: printenv
      - run: sudo apt-get install sqlite3
      - run: sudo apt-get install g++ build-essential -y
      - run: npm i
      - run: npm test
